/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#c0c4ea",
        "surface-bright": "#353944",
        "surface-container-high": "#262a34",
        "on-tertiary-fixed": "#000767",
        "on-error-container": "#ffdad6",
        "surface-dim": "#0f131d",
        "on-secondary": "#292e4c",
        "primary-container": "#8083ff",
        "tertiary-fixed-dim": "#bdc2ff",
        "outline-variant": "#464554",
        "on-secondary-container": "#b2b6db",
        "surface-container-highest": "#31353f",
        "background": "#050811",
        "surface-container": "#1a1f3c",
        "on-primary-container": "#0d0096",
        "secondary-container": "#424766",
        "primary-fixed-dim": "#c0c1ff",
        "surface": "#0f131d",
        "secondary-fixed-dim": "#c0c4ea",
        "tertiary": "#bdc2ff",
        "secondary-fixed": "#dee0ff",
        "error": "#ffb4ab",
        "outline": "#908fa0",
        "surface-variant": "#31353f",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary": "#1000a9",
        "on-tertiary-fixed-variant": "#2f3aa3",
        "on-surface": "#dfe2f0",
        "on-background": "#dfe2f0",
        "on-primary-fixed": "#07006c",
        "on-tertiary": "#131e8c",
        "inverse-primary": "#494bd6",
        "inverse-on-surface": "#2d303b",
        "primary-fixed": "#e1e0ff",
        "on-surface-variant": "#c7c4d7",
        "tertiary-fixed": "#e0e0ff",
        "primary": "#c0c1ff",
        "surface-container-lowest": "#0a0e17",
        "error-container": "#93000a",
        "inverse-surface": "#dfe2f0",
        "on-tertiary-container": "#081486",
        "on-secondary-fixed-variant": "#404564",
        "tertiary-container": "#7c87f3",
        "on-error": "#690005",
        "on-secondary-fixed": "#141936",
        "surface-tint": "#c0c1ff",
        "surface-container-low": "#181b25",
        "nebula-purple": "#8b5cf6",
        "nebula-glow": "rgba(139, 92, 246, 0.15)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "element-gap": "4px",
        "toolbar-height": "40px",
        "unit": "4px",
        "header-height": "48px",
        "panel-padding": "8px",
        "timeline-height": "240px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "ui-label-bold": ["Inter", "sans-serif"],
        "ui-label-md": ["Inter", "sans-serif"],
        "panel-header": ["Inter", "sans-serif"],
        "ui-label-sm": ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "code-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "ui-label-bold": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "ui-label-md": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "panel-header": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "ui-label-sm": ["10px", { "lineHeight": "12px", "fontWeight": "400" }],
        "mono-code": ["11px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
